### ISSUE TITLE
Some peers are attempted to be loaded before they are saved

### ISSUE THREAD

**Issue by hclivess** [hclivess/nado#38]
```
2022-12-15 11:10:58 INFO Failed to load peer 146.190.240.92 from drive: [Errno 2] No such file or directory: '/root/nado/peers/MTQ2LjE5MC4yNDAuOTI=.dat'
Traceback (most recent call last):
  File "/root/nado/loops/consensus_loop.py", line 148, in run
    self.average_trust = get_average_int(
  File "/root/nado/peer_ops.py", line 273, in get_average_int
    return int(sum(list_of_values) / len(list_of_values))
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by hclivess** [comment]
related:

```
Traceback (most recent call last):
  File "/root/nado/loops/peer_loop.py", line 120, in run
    self.purge_peers()
  File "/root/nado/loops/peer_loop.py", line 85, in purge_peers
    self.consensus.trust_pool[entry] -= 1000
TypeError: unsupported operand type(s) for -=: 'NoneType' and 'int'
2022-12-15 11:12:37 ERROR Error in peer loop: unsupported operand type(s) for -=: 'NoneType' and 'int' None
```

**Comment by hclivess** [comment]
related:

```
2022-12-15 11:17:22 ERROR Error in consensus loop: unsupported operand type(s) for +: 'int' and 'NoneType' None
2022-12-15 11:17:23 INFO Failed to load peer 170.64.156.85 from drive: [Errno 2] No such file or directory: '/root/nado/peers/MTcwLjY0LjE1Ni44NQ==.dat'
2022-12-15 11:17:23 INFO Error: One of the values to hash is empty
Traceback (most recent call last):
  File "/root/nado/loops/core_loop.py", line 420, in run
    self.normal_mode()
  File "/root/nado/loops/core_loop.py", line 108, in normal_mode
    block_candidate = get_block_candidate(block_producers=self.memserver.block_producers,
  File "/root/nado/block_ops.py", line 68, in get_block_candidate
    best_producer = pick_best_producer(block_producers,
  File "/root/nado/block_ops.py", line 395, in pick_best_producer
    block_penalty = get_penalty(producer_address=producer_address,
  File "/root/nado/block_ops.py", line 369, in get_penalty
    hash_penalty = get_hash_penalty(a=producer_address, b=block_hash)
  File "/root/nado/block_ops.py", line 18, in get_hash_penalty
    assert a and b, "One of the values to hash is empty"
AssertionError: One of the values to hash is empty
```
